- name: Prepare NixOS installer
  hosts: localhost
  gather_facts: false

  vars:
    installer_ip: "192.168.1.210"

  tasks:
    - name: Add installer to Ansible inventory
      ansible.builtin.add_host:
        name: nixos-installer
        groups: installer
        ansible_host: "{{ installer_ip }}"
        ansible_user: root
        ansible_ssh_private_key_file: "{{ lookup('env', 'NIXOS_INSTALLER_KEY') }}"

- name: Partition NixOS disk
  hosts: installer
  gather_facts: false

  vars:
    install_disk: /dev/sda

  tasks:
    - name: Verify installation disk
      ansible.builtin.assert:
        that:
          - install_disk == "/dev/sda"
        fail_msg: "Refusing to partition unexpected disk: {{ install_disk }}"

    - name: Create BIOS boot partition
      community.general.parted:
        device: "{{ install_disk }}"
        number: 1
        label: gpt
        part_start: "1MiB"
        part_end: "2MiB"
        flags:
          - bios_grub
        state: present

    - name: Create root partition
      community.general.parted:
        device: "{{ install_disk }}"
        number: 2
        label: gpt
        part_start: "2MiB"
        part_end: "100%"
        state: present

    - name: Format root partition
      community.general.filesystem:
        dev: "{{ install_disk }}2"
        fstype: ext4
      
    - name:  Mount root File system
      ansible.posix.mount:
        path: /mnt
        src: "{{ install_disk }}2"
        fstype: ext4
        state: ephemeral

    - name: Generate hardware configuration
      ansible.builtin.command:
        cmd: nixos-generate-config --root /mnt

    - name: Create NixOS configuration
      ansible.builtin.copy:
        dest: /mnt/etc/nixos/configuration.nix
        content: |
          { config, lib, pkgs, ... }:
    
          {
            imports = [
              ./hardware-configuration.nix
            ];

            environment.systemPackages = with pkgs; [
                python3
                git
            ];

            # Use the GRUB 2 boot loader.
            boot.loader.grub.enable = true;
            # boot.loader.grub.efiSupport = true;
            # boot.loader.grub.efiInstallAsRemovable = true;
            # boot.loader.efi.efiSysMountPoint = "/boot/efi";
            # Define on which hard drive you want to install Grub.
            boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only
    
            services.openssh.enable = true;
    
            users.users.admin = {
              isNormalUser = true;
              extraGroups = [ "wheel" ];
              openssh.authorizedKeys.keys = [
                "{{ lookup('file', lookup('env', 'NIXOS_DEPLOYMENT_PUBLIC_KEY')) }}"
              ];
            };

            security.sudo.wheelNeedsPassword = false;
          }

    - name: Enable Nix experimental features
      ansible.builtin.copy:
        dest: /etc/nix/nix.conf
        content: |
          experimental-features = nix-command flakes

    - name: Install NixOS
      ansible.builtin.command:
        cmd: nixos-install --root /mnt --no-root-passwd